# Generated by Django 2.1.3 on 2019-01-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='maxMemberNum',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='activity',
            name='score',
            field=models.FloatField(default=5),
        ),
    ]
